version: "3.9"

services:
  backend:
    build: ./backend
    container_name: 'backend'
    networks:
      - crypto_project
#    ports:
#      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: 'frontend'
    volumes:
      - frontend_dist:/app/dist
    networks:
      - crypto_project
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: 'nginx'
    networks:
      - crypto_project
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

networks:
  crypto_project:
    driver: bridge

volumes:
  frontend_dist:
    driver: local