services:
  backend:
    build: ./backend
    container_name: 'backend'
    networks:
      - crypto_project

  frontend:
    build: ./frontend
    container_name: 'frontend'
    volumes:
      - frontend_dist:/app/dist
    networks:
      - crypto_project
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: 'nginx'
    networks:
      - crypto_project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - frontend
      - backend

networks:
  crypto_project:
    driver: bridge

volumes:
  frontend_dist:
    driver: local